-- RunStrict Day 2 / 40 (2026-01-16)
-- Generated by simulate_day.py

-- === DAY 2 RUNS (47 runs) ===
INSERT INTO public.run_history (id, user_id, run_date, start_time, end_time, distance_km, duration_seconds, avg_pace_min_per_km, flip_count, flip_points, team_at_run, cv) VALUES
  ('3224a982-068c-461d-ac84-5aa4dcbd4aa7', 'aaaaaaaa-0000-0000-0000-000000000000', '2026-01-16', '2026-01-16 05:37:00+00', '2026-01-16 06:40:11+00', 11.79, 3791, 5.36, 14, 28, 'red', 3.9),
  ('7f60edbb-a3bb-40eb-97b3-5d040c5ce377', 'aaaaaaaa-0001-0001-0001-000000000001', '2026-01-16', '2026-01-16 21:52:00+00', '2026-01-16 22:55:09+00', 12.53, 3789, 5.04, 4, 8, 'red', 8.0),
  ('8f7df47a-4421-4a27-b7ff-b757328c3efd', 'aaaaaaaa-0002-0002-0002-000000000002', '2026-01-16', '2026-01-16 07:07:00+00', '2026-01-16 07:45:58+00', 8.24, 2338, 4.73, 4, 8, 'red', 5.4),
  ('c56ac3b4-d85a-4d86-b61c-bf81b7eb54c4', 'aaaaaaaa-0003-0003-0003-000000000003', '2026-01-16', '2026-01-16 16:02:00+00', '2026-01-16 16:55:22+00', 11.73, 3202, 4.55, 5, 10, 'red', 7.4),
  ('68c655de-bda8-4aae-813c-2cae01c5ba61', 'aaaaaaaa-0004-0004-0004-000000000004', '2026-01-16', '2026-01-16 15:28:00+00', '2026-01-16 16:20:45+00', 10.97, 3165, 4.81, 4, 4, 'red', 8.0),
  ('64629a23-0234-4f4e-b55e-558057425266', 'aaaaaaaa-0005-0005-0005-000000000005', '2026-01-16', '2026-01-16 14:36:00+00', '2026-01-16 15:47:22+00', 14.19, 4282, 5.03, 5, 10, 'red', 3.2),
  ('cab45782-5a61-47a1-a999-42fc9e4def78', 'aaaaaaaa-0006-0006-0006-000000000006', '2026-01-16', '2026-01-16 05:02:00+00', '2026-01-16 06:13:10+00', 14.35, 4270, 4.96, 5, 5, 'red', 6.1),
  ('fa1a7c4b-a035-47e2-80e1-b5de16efb8ac', 'aaaaaaaa-0007-0007-0007-000000000007', '2026-01-16', '2026-01-16 17:21:00+00', '2026-01-16 18:17:03+00', 10.46, 3363, 5.36, 5, 10, 'red', 4.4),
  ('ad7f7950-b7e9-4a5b-ad31-3b18f488cdf8', 'aaaaaaaa-0008-0008-0008-000000000008', '2026-01-16', '2026-01-16 13:02:00+00', '2026-01-16 14:03:06+00', 13.0, 3666, 4.7, 2, 2, 'red', 6.1),
  ('2f7da6bb-1299-448f-9a8e-dcc7064d54a1', 'aaaaaaaa-0009-0009-0009-000000000009', '2026-01-16', '2026-01-16 18:03:00+00', '2026-01-16 19:22:22+00', 14.78, 4762, 5.37, 4, 4, 'red', 6.0),
  ('dc8f9b47-de72-43e2-9f75-1520f6b1e115', 'aaaaaaaa-0011-0011-0011-000000000011', '2026-01-16', '2026-01-16 17:11:00+00', '2026-01-16 17:58:44+00', 7.8, 2864, 6.12, 1, 1, 'red', 12.9),
  ('5ab725b9-5052-4f53-8147-94a0717bac56', 'aaaaaaaa-0013-0013-0013-000000000013', '2026-01-16', '2026-01-16 11:35:00+00', '2026-01-16 12:03:05+00', 5.09, 1685, 5.52, 3, 3, 'red', 5.2),
  ('e10e88eb-123c-43ba-915d-32cf99bc756a', 'aaaaaaaa-0014-0014-0014-000000000014', '2026-01-16', '2026-01-16 07:45:00+00', '2026-01-16 08:14:59+00', 5.88, 1799, 5.1, 3, 3, 'red', 5.2),
  ('33fe5d5b-87fe-41ec-b13d-2abd545a20ae', 'aaaaaaaa-0015-0015-0015-000000000015', '2026-01-16', '2026-01-16 20:30:00+00', '2026-01-16 21:26:21+00', 9.75, 3381, 5.78, 3, 3, 'red', 5.1),
  ('b95e995c-4f5d-4205-a323-9cd47ccbe119', 'aaaaaaaa-0016-0016-0016-000000000016', '2026-01-16', '2026-01-16 20:47:00+00', '2026-01-16 21:19:51+00', 6.2, 1971, 5.3, 0, 0, 'red', 9.6),
  ('77a94cff-1fd9-4449-9427-95f1d986f2e7', 'aaaaaaaa-0017-0017-0017-000000000017', '2026-01-16', '2026-01-16 16:00:00+00', '2026-01-16 16:39:31+00', 7.89, 2371, 5.01, 1, 1, 'red', 5.7),
  ('c2fd164c-4015-41e2-861e-9a871c53702a', 'aaaaaaaa-0018-0018-0018-000000000018', '2026-01-16', '2026-01-16 13:44:00+00', '2026-01-16 14:27:41+00', 7.68, 2621, 5.69, 4, 4, 'red', 8.2),
  ('01358895-8832-44a0-9e6c-a773b15bbc8e', 'aaaaaaaa-0020-0020-0020-000000000020', '2026-01-16', '2026-01-16 17:54:00+00', '2026-01-16 18:23:58+00', 5.9, 1798, 5.08, 3, 3, 'red', 5.6),
  ('6c6217b5-b4d4-4a1d-819b-6f2eae0bac53', 'aaaaaaaa-0022-0022-0022-000000000022', '2026-01-16', '2026-01-16 17:38:00+00', '2026-01-16 18:30:52+00', 9.46, 3172, 5.59, 1, 1, 'red', 11.1),
  ('d7dcdfe9-77b5-4590-a68e-97288204ac03', 'aaaaaaaa-0023-0023-0023-000000000023', '2026-01-16', '2026-01-16 07:29:00+00', '2026-01-16 08:16:58+00', 7.64, 2878, 6.28, 2, 2, 'red', 9.0),
  ('b082ea18-e772-4a47-918a-3f84f71de120', 'aaaaaaaa-0024-0024-0024-000000000024', '2026-01-16', '2026-01-16 15:50:00+00', '2026-01-16 16:14:11+00', 4.15, 1451, 5.83, 1, 1, 'red', 10.0),
  ('0d0b0272-bfd9-4da6-afb5-5e21c82d1f2e', 'aaaaaaaa-0025-0025-0025-000000000025', '2026-01-16', '2026-01-16 21:49:00+00', '2026-01-16 22:22:51+00', 5.57, 2031, 6.08, 1, 1, 'red', 12.5),
  ('aa478a7f-369c-48a3-81ee-b689c972d9ec', 'aaaaaaaa-0028-0028-0028-000000000028', '2026-01-16', '2026-01-16 16:21:00+00', '2026-01-16 17:11:50+00', 8.78, 3050, 5.79, 0, 0, 'red', 14.0),
  ('574ac871-b6fa-4dd5-88bc-6cac915015e0', 'aaaaaaaa-0030-0030-0030-000000000030', '2026-01-16', '2026-01-16 15:01:00+00', '2026-01-16 15:36:15+00', 6.23, 2115, 5.66, 1, 1, 'red', 10.8),
  ('e1340052-d26e-49cf-9685-c02d20129be1', 'aaaaaaaa-0031-0031-0031-000000000031', '2026-01-16', '2026-01-16 15:04:00+00', '2026-01-16 15:38:54+00', 6.5, 2094, 5.37, 3, 3, 'red', 7.7),
  ('35ea5574-ae95-459d-b0ba-b7f730ea65d8', 'aaaaaaaa-0032-0032-0032-000000000032', '2026-01-16', '2026-01-16 19:46:00+00', '2026-01-16 20:34:03+00', 8.77, 2883, 5.48, 1, 1, 'red', 10.3),
  ('d1024f62-6d7e-41ee-b61e-2b44eab4b075', 'aaaaaaaa-0033-0033-0033-000000000033', '2026-01-16', '2026-01-16 05:25:00+00', '2026-01-16 05:51:27+00', 4.5, 1587, 5.88, 1, 1, 'red', 6.1),
  ('6487c5dd-ecf2-46a9-b600-3d1c23b16c3c', 'aaaaaaaa-0035-0035-0035-000000000035', '2026-01-16', '2026-01-16 06:34:00+00', '2026-01-16 07:03:14+00', 5.26, 1754, 5.56, 2, 2, 'red', 6.8),
  ('61fb86b6-a6bc-46e3-a061-64096debbd83', 'aaaaaaaa-0036-0036-0036-000000000036', '2026-01-16', '2026-01-16 12:10:00+00', '2026-01-16 12:58:14+00', 9.33, 2894, 5.17, 2, 2, 'red', 8.7),
  ('28d86d1b-a6f5-47b5-80da-b5d599ae83d5', 'aaaaaaaa-0037-0037-0037-000000000037', '2026-01-16', '2026-01-16 08:31:00+00', '2026-01-16 09:18:19+00', 7.43, 2839, 6.37, 2, 2, 'red', 9.2),
  ('19ecf0bd-ee86-4e9c-ad49-dc50b4e375f8', 'aaaaaaaa-0038-0038-0038-000000000038', '2026-01-16', '2026-01-16 06:35:00+00', '2026-01-16 07:29:00+00', 8.81, 3240, 6.13, 0, 0, 'red', 5.1),
  ('78096856-727f-4a28-9353-da4ed09cbfc3', 'aaaaaaaa-0039-0039-0039-000000000039', '2026-01-16', '2026-01-16 18:26:00+00', '2026-01-16 18:48:52+00', 4.26, 1372, 5.37, 0, 0, 'red', 10.2),
  ('7884d1d4-08d2-4489-b765-966de8a7705c', 'aaaaaaaa-0042-0042-0042-000000000042', '2026-01-16', '2026-01-16 12:14:00+00', '2026-01-16 13:10:24+00', 9.37, 3384, 6.02, 20, 60, 'blue', 13.5),
  ('0ff2dc54-6572-4c00-93f7-5df91c0f5815', 'aaaaaaaa-0045-0045-0045-000000000045', '2026-01-16', '2026-01-16 19:18:00+00', '2026-01-16 19:58:01+00', 7.58, 2401, 5.28, 9, 27, 'blue', 9.7),
  ('4003a41a-417c-4ea2-a31e-8a552027d200', 'aaaaaaaa-0048-0048-0048-000000000048', '2026-01-16', '2026-01-16 10:32:00+00', '2026-01-16 11:20:56+00', 9.34, 2936, 5.24, 11, 33, 'blue', 9.0),
  ('e847967e-7747-4029-a7fa-8a3bc25fa0ad', 'aaaaaaaa-0053-0053-0053-000000000053', '2026-01-16', '2026-01-16 20:24:00+00', '2026-01-16 20:42:47+00', 3.02, 1127, 6.22, 3, 9, 'blue', 20.7),
  ('46fbb187-0b63-4856-98e0-1055850825fe', 'aaaaaaaa-0055-0055-0055-000000000055', '2026-01-16', '2026-01-16 20:09:00+00', '2026-01-16 20:25:23+00', 2.59, 983, 6.33, 0, 0, 'blue', 12.6),
  ('217828fd-9a0d-42e6-8665-91d5fedd45a4', 'aaaaaaaa-0057-0057-0057-000000000057', '2026-01-16', '2026-01-16 19:37:00+00', '2026-01-16 19:50:17+00', 2.19, 797, 6.07, 2, 6, 'blue', 13.7),
  ('801530e1-d772-4ddd-9865-027a6a367b81', 'aaaaaaaa-0061-0061-0061-000000000061', '2026-01-16', '2026-01-16 14:18:00+00', '2026-01-16 14:36:58+00', 3.1, 1138, 6.12, 3, 9, 'blue', 15.6),
  ('9c3fcba9-60b4-449c-b8ca-0484e93d5bfb', 'aaaaaaaa-0063-0063-0063-000000000063', '2026-01-16', '2026-01-16 20:37:00+00', '2026-01-16 21:08:47+00', 5.07, 1907, 6.27, 1, 3, 'blue', 13.6),
  ('dd02089f-8404-4198-bbf3-f1ecd57193ca', 'aaaaaaaa-0066-0066-0066-000000000066', '2026-01-16', '2026-01-16 08:29:00+00', '2026-01-16 09:09:52+00', 5.74, 2452, 7.12, 1, 3, 'blue', 13.9),
  ('1e6c2ff1-45b0-4433-b7f0-e07333f88e11', 'aaaaaaaa-0073-0073-0073-000000000073', '2026-01-16', '2026-01-16 15:04:00+00', '2026-01-16 15:24:26+00', 2.86, 1226, 7.15, 4, 12, 'blue', 13.5),
  ('54c374b0-9e23-483b-a1c9-aae51c01aeb6', 'aaaaaaaa-0082-0082-0082-000000000082', '2026-01-16', '2026-01-16 15:51:00+00', '2026-01-16 16:22:44+00', 4.6, 1904, 6.9, 10, 10, 'purple', 18.5),
  ('1ce9fc85-bbfb-41d7-8c3a-75485e7c30df', 'aaaaaaaa-0083-0083-0083-000000000083', '2026-01-16', '2026-01-16 14:41:00+00', '2026-01-16 15:05:45+00', 3.4, 1485, 7.28, 6, 6, 'purple', 11.4),
  ('7f7ad6e8-696e-4e56-804d-454678c93fd1', 'aaaaaaaa-0084-0084-0084-000000000084', '2026-01-16', '2026-01-16 20:03:00+00', '2026-01-16 20:43:59+00', 5.95, 2459, 6.89, 10, 10, 'purple', 10.9),
  ('80d8aa7d-4549-499e-b4eb-568972f66fe0', 'aaaaaaaa-0087-0087-0087-000000000087', '2026-01-16', '2026-01-16 08:30:00+00', '2026-01-16 08:49:28+00', 2.69, 1168, 7.24, 4, 4, 'purple', 28.4),
  ('551a3f76-8b1d-484c-9c6d-21972718d4a5', 'aaaaaaaa-0091-0091-0091-000000000091', '2026-01-16', '2026-01-16 15:06:00+00', '2026-01-16 15:32:07+00', 3.38, 1567, 7.73, 5, 5, 'purple', 28.7);

-- === HEX MAP (156 hexes) ===
INSERT INTO public.hexes (id, last_runner_team) VALUES
  ('8928308282bffff', 'red'),
  ('89283082813ffff', 'red'),
  ('89283082a37ffff', 'red'),
  ('8928308280fffff', 'red'),
  ('89283082833ffff', 'blue'),
  ('892830829bfffff', 'purple'),
  ('89283082a3bffff', 'red'),
  ('8928308287fffff', 'blue'),
  ('89283082a43ffff', 'red'),
  ('8928308282fffff', 'blue'),
  ('89283082827ffff', 'red'),
  ('89283082807ffff', 'purple'),
  ('89283082a4bffff', 'blue'),
  ('892830828abffff', 'blue'),
  ('89283082837ffff', 'red'),
  ('8928308283fffff', 'red'),
  ('89283082817ffff', 'red'),
  ('89283082953ffff', 'purple'),
  ('8928308281bffff', 'red'),
  ('89283082a3fffff', 'red'),
  ('89283082913ffff', 'blue'),
  ('89283082a5bffff', 'red'),
  ('89283082a6bffff', 'red'),
  ('8928308296fffff', 'red'),
  ('8928308289fffff', 'blue'),
  ('89283082a5fffff', 'red'),
  ('8928308295bffff', 'purple'),
  ('892830829d3ffff', 'purple'),
  ('8928308298bffff', 'purple'),
  ('89283082a53ffff', 'red'),
  ('8928308299fffff', 'red'),
  ('89283082a6fffff', 'red'),
  ('8928308294fffff', 'red'),
  ('89283082a4fffff', 'purple'),
  ('892830828c3ffff', 'red'),
  ('89283082843ffff', 'red'),
  ('89283082a67ffff', 'red'),
  ('8928308298fffff', 'purple'),
  ('89283082803ffff', 'purple'),
  ('89283082a47ffff', 'red'),
  ('89283082a0bffff', 'blue'),
  ('89283082a03ffff', 'red'),
  ('8928308281fffff', 'purple'),
  ('892830829efffff', 'red'),
  ('89283082893ffff', 'red'),
  ('892830829e7ffff', 'purple'),
  ('8928308289bffff', 'blue'),
  ('89283082823ffff', 'blue'),
  ('89283082847ffff', 'red'),
  ('89283082a33ffff', 'red'),
  ('8928308286fffff', 'blue'),
  ('8928308285bffff', 'red'),
  ('892830828efffff', 'blue'),
  ('892830829afffff', 'red'),
  ('8928308280bffff', 'red'),
  ('8928308283bffff', 'blue'),
  ('892830828f3ffff', 'blue'),
  ('892830828bbffff', 'blue'),
  ('89283082a57ffff', 'red'),
  ('892830828dbffff', 'blue'),
  ('8928308290bffff', 'red'),
  ('892830828bfffff', 'blue'),
  ('89283082a0fffff', 'purple'),
  ('89283082a63ffff', 'red'),
  ('892830828cfffff', 'blue'),
  ('892830828e7ffff', 'blue'),
  ('89283082853ffff', 'blue'),
  ('892830829c7ffff', 'blue'),
  ('892830828b7ffff', 'red'),
  ('89283082873ffff', 'red'),
  ('8928308284fffff', 'red'),
  ('89283082857ffff', 'red'),
  ('89283082943ffff', 'purple'),
  ('892830828dfffff', 'blue'),
  ('89283082947ffff', 'purple'),
  ('892830828b3ffff', 'blue'),
  ('8928308287bffff', 'blue'),
  ('89283082973ffff', 'purple'),
  ('8928308284bffff', 'red'),
  ('89283082967ffff', 'purple'),
  ('89283082927ffff', 'purple'),
  ('89283082863ffff', 'red'),
  ('892830829f3ffff', 'blue'),
  ('8928308296bffff', 'purple'),
  ('892830828f7ffff', 'blue'),
  ('8928308285fffff', 'purple'),
  ('8928308286bffff', 'red'),
  ('892830828a7ffff', 'purple'),
  ('89283082997ffff', 'purple'),
  ('89283082867ffff', 'red'),
  ('892830828d3ffff', 'blue'),
  ('892830828ffffff', 'blue'),
  ('892830829cfffff', 'red'),
  ('8928308297bffff', 'purple'),
  ('89283082877ffff', 'red'),
  ('892830828ebffff', 'blue'),
  ('892830829dbffff', 'blue'),
  ('89283082933ffff', 'purple'),
  ('89283082a1bffff', 'red'),
  ('89283082a27ffff', 'red'),
  ('89283082a2fffff', 'blue'),
  ('89283082887ffff', 'blue'),
  ('8928308288bffff', 'blue'),
  ('89283082917ffff', 'purple'),
  ('8928308293fffff', 'red'),
  ('89283082983ffff', 'purple'),
  ('892830829a7ffff', 'purple'),
  ('89283082963ffff', 'purple'),
  ('892830828fbffff', 'blue'),
  ('89283082987ffff', 'purple'),
  ('89283082897ffff', 'blue'),
  ('89283082883ffff', 'blue'),
  ('892830829d7ffff', 'red'),
  ('8928308288fffff', 'blue'),
  ('89283082a1fffff', 'red'),
  ('892830828cbffff', 'blue'),
  ('892830829b3ffff', 'red'),
  ('89283082a07ffff', 'red'),
  ('89283082923ffff', 'purple'),
  ('89283082907ffff', 'blue'),
  ('892830829fbffff', 'red'),
  ('8928308291bffff', 'blue'),
  ('89283082a23ffff', 'red'),
  ('89283082a2bffff', 'red'),
  ('892830828a3ffff', 'blue'),
  ('892830829c3ffff', 'blue'),
  ('892830829a3ffff', 'blue'),
  ('892830829e3ffff', 'red'),
  ('892830828c7ffff', 'blue'),
  ('892830829dfffff', 'blue'),
  ('89283082957ffff', 'blue'),
  ('892830828d7ffff', 'blue'),
  ('89283082903ffff', 'blue'),
  ('89283082a17ffff', 'red'),
  ('8928308299bffff', 'red'),
  ('892830828e3ffff', 'blue'),
  ('892830828afffff', 'blue'),
  ('892830829f7ffff', 'red'),
  ('89283082937ffff', 'purple'),
  ('892830829b7ffff', 'blue'),
  ('8928308292fffff', 'purple'),
  ('8928308293bffff', 'purple'),
  ('8928308290fffff', 'blue'),
  ('8928308294bffff', 'purple'),
  ('89283082977ffff', 'purple'),
  ('8928308295fffff', 'purple'),
  ('8928308292bffff', 'blue'),
  ('8928308291fffff', 'blue'),
  ('892830829ffffff', 'red'),
  ('8928308297fffff', 'purple'),
  ('892830829ebffff', 'red'),
  ('892830829cbffff', 'red'),
  ('89283082993ffff', 'blue'),
  ('892830829abffff', 'blue'),
  ('892830829bbffff', 'red'),
  ('89283082a13ffff', 'blue')
ON CONFLICT (id) DO UPDATE SET last_runner_team = EXCLUDED.last_runner_team;

-- === UPDATE USER SEASON STATS ===
UPDATE public.users SET season_points = 73, total_distance_km = 18.87, total_runs = 2, avg_pace_min_per_km = 5.54, avg_cv = 12.1 WHERE id = 'aaaaaaaa-0042-0042-0042-000000000042';
UPDATE public.users SET season_points = 50, total_distance_km = 24.66, total_runs = 2, avg_pace_min_per_km = 5.0, avg_cv = 4.6 WHERE id = 'aaaaaaaa-0000-0000-0000-000000000000';
UPDATE public.users SET season_points = 36, total_distance_km = 14.74, total_runs = 2, avg_pace_min_per_km = 5.82, avg_cv = 10.2 WHERE id = 'aaaaaaaa-0048-0048-0048-000000000048';
UPDATE public.users SET season_points = 35, total_distance_km = 15.75, total_runs = 2, avg_pace_min_per_km = 5.67, avg_cv = 10.1 WHERE id = 'aaaaaaaa-0045-0045-0045-000000000045';
UPDATE public.users SET season_points = 28, total_distance_km = 27.22, total_runs = 2, avg_pace_min_per_km = 5.13, avg_cv = 5.6 WHERE id = 'aaaaaaaa-0001-0001-0001-000000000001';
UPDATE public.users SET season_points = 23, total_distance_km = 25.44, total_runs = 2, avg_pace_min_per_km = 4.56, avg_cv = 6.8 WHERE id = 'aaaaaaaa-0003-0003-0003-000000000003';
UPDATE public.users SET season_points = 17, total_distance_km = 8.64, total_runs = 1, avg_pace_min_per_km = 5.13, avg_cv = 11.7 WHERE id = 'aaaaaaaa-0040-0040-0040-000000000040';
UPDATE public.users SET season_points = 17, total_distance_km = 8.28, total_runs = 2, avg_pace_min_per_km = 7.02, avg_cv = 11.1 WHERE id = 'aaaaaaaa-0083-0083-0083-000000000083';
UPDATE public.users SET season_points = 16, total_distance_km = 18.08, total_runs = 2, avg_pace_min_per_km = 4.68, avg_cv = 6.1 WHERE id = 'aaaaaaaa-0002-0002-0002-000000000002';
UPDATE public.users SET season_points = 16, total_distance_km = 26.5, total_runs = 2, avg_pace_min_per_km = 5.02, avg_cv = 5.2 WHERE id = 'aaaaaaaa-0005-0005-0005-000000000005';
UPDATE public.users SET season_points = 15, total_distance_km = 23.74, total_runs = 2, avg_pace_min_per_km = 5.38, avg_cv = 5.6 WHERE id = 'aaaaaaaa-0007-0007-0007-000000000007';
UPDATE public.users SET season_points = 13, total_distance_km = 5.39, total_runs = 2, avg_pace_min_per_km = 7.08, avg_cv = 12.9 WHERE id = 'aaaaaaaa-0073-0073-0073-000000000073';
UPDATE public.users SET season_points = 11, total_distance_km = 8.27, total_runs = 1, avg_pace_min_per_km = 5.0, avg_cv = 13.8 WHERE id = 'aaaaaaaa-0041-0041-0041-000000000041';
UPDATE public.users SET season_points = 11, total_distance_km = 7.29, total_runs = 2, avg_pace_min_per_km = 6.47, avg_cv = 17.9 WHERE id = 'aaaaaaaa-0053-0053-0053-000000000053';
UPDATE public.users SET season_points = 10, total_distance_km = 4.6, total_runs = 1, avg_pace_min_per_km = 6.9, avg_cv = 18.5 WHERE id = 'aaaaaaaa-0082-0082-0082-000000000082';
UPDATE public.users SET season_points = 10, total_distance_km = 5.95, total_runs = 1, avg_pace_min_per_km = 6.89, avg_cv = 10.9 WHERE id = 'aaaaaaaa-0084-0084-0084-000000000084';
UPDATE public.users SET season_points = 9, total_distance_km = 3.1, total_runs = 1, avg_pace_min_per_km = 6.12, avg_cv = 15.6 WHERE id = 'aaaaaaaa-0061-0061-0061-000000000061';
UPDATE public.users SET season_points = 8, total_distance_km = 25.36, total_runs = 2, avg_pace_min_per_km = 4.98, avg_cv = 4.6 WHERE id = 'aaaaaaaa-0006-0006-0006-000000000006';
UPDATE public.users SET season_points = 8, total_distance_km = 23.01, total_runs = 2, avg_pace_min_per_km = 5.13, avg_cv = 4.8 WHERE id = 'aaaaaaaa-0009-0009-0009-000000000009';
UPDATE public.users SET season_points = 7, total_distance_km = 15.38, total_runs = 2, avg_pace_min_per_km = 5.25, avg_cv = 9.8 WHERE id = 'aaaaaaaa-0014-0014-0014-000000000014';
UPDATE public.users SET season_points = 7, total_distance_km = 9.4, total_runs = 1, avg_pace_min_per_km = 5.76, avg_cv = 5.1 WHERE id = 'aaaaaaaa-0049-0049-0049-000000000049';
UPDATE public.users SET season_points = 6, total_distance_km = 22.02, total_runs = 2, avg_pace_min_per_km = 4.9, avg_cv = 8.0 WHERE id = 'aaaaaaaa-0004-0004-0004-000000000004';
UPDATE public.users SET season_points = 6, total_distance_km = 13.91, total_runs = 2, avg_pace_min_per_km = 5.51, avg_cv = 6.4 WHERE id = 'aaaaaaaa-0013-0013-0013-000000000013';
UPDATE public.users SET season_points = 6, total_distance_km = 15.65, total_runs = 2, avg_pace_min_per_km = 6.09, avg_cv = 6.0 WHERE id = 'aaaaaaaa-0015-0015-0015-000000000015';
UPDATE public.users SET season_points = 6, total_distance_km = 12.31, total_runs = 2, avg_pace_min_per_km = 5.87, avg_cv = 11.8 WHERE id = 'aaaaaaaa-0023-0023-0023-000000000023';
UPDATE public.users SET season_points = 6, total_distance_km = 9.08, total_runs = 2, avg_pace_min_per_km = 6.58, avg_cv = 18.2 WHERE id = 'aaaaaaaa-0063-0063-0063-000000000063';
UPDATE public.users SET season_points = 6, total_distance_km = 2.19, total_runs = 1, avg_pace_min_per_km = 6.07, avg_cv = 13.7 WHERE id = 'aaaaaaaa-0057-0057-0057-000000000057';
UPDATE public.users SET season_points = 5, total_distance_km = 15.55, total_runs = 2, avg_pace_min_per_km = 5.94, avg_cv = 13.4 WHERE id = 'aaaaaaaa-0025-0025-0025-000000000025';
UPDATE public.users SET season_points = 5, total_distance_km = 12.87, total_runs = 2, avg_pace_min_per_km = 5.59, avg_cv = 7.4 WHERE id = 'aaaaaaaa-0035-0035-0035-000000000035';
UPDATE public.users SET season_points = 5, total_distance_km = 3.38, total_runs = 1, avg_pace_min_per_km = 6.78, avg_cv = 23.1 WHERE id = 'aaaaaaaa-0072-0072-0072-000000000072';
UPDATE public.users SET season_points = 5, total_distance_km = 3.38, total_runs = 1, avg_pace_min_per_km = 7.73, avg_cv = 28.7 WHERE id = 'aaaaaaaa-0091-0091-0091-000000000091';
UPDATE public.users SET season_points = 4, total_distance_km = 23.44, total_runs = 2, avg_pace_min_per_km = 4.63, avg_cv = 4.9 WHERE id = 'aaaaaaaa-0008-0008-0008-000000000008';
UPDATE public.users SET season_points = 4, total_distance_km = 16.19, total_runs = 2, avg_pace_min_per_km = 6.04, avg_cv = 10.8 WHERE id = 'aaaaaaaa-0018-0018-0018-000000000018';
UPDATE public.users SET season_points = 4, total_distance_km = 11.65, total_runs = 2, avg_pace_min_per_km = 5.48, avg_cv = 9.9 WHERE id = 'aaaaaaaa-0020-0020-0020-000000000020';
UPDATE public.users SET season_points = 4, total_distance_km = 11.84, total_runs = 2, avg_pace_min_per_km = 5.78, avg_cv = 7.9 WHERE id = 'aaaaaaaa-0024-0024-0024-000000000024';
UPDATE public.users SET season_points = 4, total_distance_km = 15.09, total_runs = 2, avg_pace_min_per_km = 5.48, avg_cv = 12.9 WHERE id = 'aaaaaaaa-0030-0030-0030-000000000030';
UPDATE public.users SET season_points = 4, total_distance_km = 13.0, total_runs = 2, avg_pace_min_per_km = 5.82, avg_cv = 7.3 WHERE id = 'aaaaaaaa-0033-0033-0033-000000000033';
UPDATE public.users SET season_points = 4, total_distance_km = 17.26, total_runs = 2, avg_pace_min_per_km = 5.69, avg_cv = 11.1 WHERE id = 'aaaaaaaa-0036-0036-0036-000000000036';
UPDATE public.users SET season_points = 4, total_distance_km = 4.92, total_runs = 1, avg_pace_min_per_km = 6.3, avg_cv = 14.9 WHERE id = 'aaaaaaaa-0043-0043-0043-000000000043';
UPDATE public.users SET season_points = 4, total_distance_km = 2.69, total_runs = 1, avg_pace_min_per_km = 7.24, avg_cv = 28.4 WHERE id = 'aaaaaaaa-0087-0087-0087-000000000087';
UPDATE public.users SET season_points = 3, total_distance_km = 8.83, total_runs = 1, avg_pace_min_per_km = 6.27, avg_cv = 10.5 WHERE id = 'aaaaaaaa-0019-0019-0019-000000000019';
UPDATE public.users SET season_points = 3, total_distance_km = 6.64, total_runs = 1, avg_pace_min_per_km = 5.78, avg_cv = 7.9 WHERE id = 'aaaaaaaa-0021-0021-0021-000000000021';
UPDATE public.users SET season_points = 3, total_distance_km = 14.32, total_runs = 2, avg_pace_min_per_km = 5.62, avg_cv = 6.8 WHERE id = 'aaaaaaaa-0031-0031-0031-000000000031';
UPDATE public.users SET season_points = 3, total_distance_km = 5.07, total_runs = 1, avg_pace_min_per_km = 6.47, avg_cv = 14.5 WHERE id = 'aaaaaaaa-0046-0046-0046-000000000046';
UPDATE public.users SET season_points = 3, total_distance_km = 4.98, total_runs = 1, avg_pace_min_per_km = 5.88, avg_cv = 5.9 WHERE id = 'aaaaaaaa-0047-0047-0047-000000000047';
UPDATE public.users SET season_points = 3, total_distance_km = 5.74, total_runs = 1, avg_pace_min_per_km = 7.12, avg_cv = 13.9 WHERE id = 'aaaaaaaa-0066-0066-0066-000000000066';
UPDATE public.users SET season_points = 2, total_distance_km = 14.85, total_runs = 2, avg_pace_min_per_km = 5.32, avg_cv = 11.4 WHERE id = 'aaaaaaaa-0016-0016-0016-000000000016';
UPDATE public.users SET season_points = 2, total_distance_km = 16.36, total_runs = 2, avg_pace_min_per_km = 5.57, avg_cv = 7.2 WHERE id = 'aaaaaaaa-0017-0017-0017-000000000017';
UPDATE public.users SET season_points = 2, total_distance_km = 13.13, total_runs = 2, avg_pace_min_per_km = 5.58, avg_cv = 13.6 WHERE id = 'aaaaaaaa-0028-0028-0028-000000000028';
UPDATE public.users SET season_points = 2, total_distance_km = 3.8, total_runs = 1, avg_pace_min_per_km = 6.57, avg_cv = 10.3 WHERE id = 'aaaaaaaa-0054-0054-0054-000000000054';
UPDATE public.users SET season_points = 2, total_distance_km = 4.06, total_runs = 1, avg_pace_min_per_km = 6.44, avg_cv = 16.6 WHERE id = 'aaaaaaaa-0071-0071-0071-000000000071';
UPDATE public.users SET season_points = 2, total_distance_km = 3.23, total_runs = 1, avg_pace_min_per_km = 7.22, avg_cv = 16.1 WHERE id = 'aaaaaaaa-0077-0077-0077-000000000077';
UPDATE public.users SET season_points = 2, total_distance_km = 7.43, total_runs = 1, avg_pace_min_per_km = 6.37, avg_cv = 9.2 WHERE id = 'aaaaaaaa-0037-0037-0037-000000000037';
UPDATE public.users SET season_points = 1, total_distance_km = 5.18, total_runs = 1, avg_pace_min_per_km = 5.68, avg_cv = 14.8 WHERE id = 'aaaaaaaa-0010-0010-0010-000000000010';
UPDATE public.users SET season_points = 1, total_distance_km = 6.1, total_runs = 1, avg_pace_min_per_km = 5.23, avg_cv = 9.7 WHERE id = 'aaaaaaaa-0026-0026-0026-000000000026';
UPDATE public.users SET season_points = 1, total_distance_km = 12.87, total_runs = 2, avg_pace_min_per_km = 5.58, avg_cv = 9.6 WHERE id = 'aaaaaaaa-0039-0039-0039-000000000039';
UPDATE public.users SET season_points = 1, total_distance_km = 6.51, total_runs = 2, avg_pace_min_per_km = 6.38, avg_cv = 15.4 WHERE id = 'aaaaaaaa-0055-0055-0055-000000000055';
UPDATE public.users SET season_points = 1, total_distance_km = 2.84, total_runs = 1, avg_pace_min_per_km = 6.99, avg_cv = 24.8 WHERE id = 'aaaaaaaa-0070-0070-0070-000000000070';
UPDATE public.users SET season_points = 1, total_distance_km = 7.8, total_runs = 1, avg_pace_min_per_km = 6.12, avg_cv = 12.9 WHERE id = 'aaaaaaaa-0011-0011-0011-000000000011';
UPDATE public.users SET season_points = 1, total_distance_km = 9.46, total_runs = 1, avg_pace_min_per_km = 5.59, avg_cv = 11.1 WHERE id = 'aaaaaaaa-0022-0022-0022-000000000022';
UPDATE public.users SET season_points = 1, total_distance_km = 8.77, total_runs = 1, avg_pace_min_per_km = 5.48, avg_cv = 10.3 WHERE id = 'aaaaaaaa-0032-0032-0032-000000000032';
UPDATE public.users SET season_points = 0, total_distance_km = 14.61, total_runs = 2, avg_pace_min_per_km = 5.99, avg_cv = 8.9 WHERE id = 'aaaaaaaa-0038-0038-0038-000000000038';
UPDATE public.users SET season_points = 0, total_distance_km = 2.12, total_runs = 1, avg_pace_min_per_km = 7.03, avg_cv = 12.4 WHERE id = 'aaaaaaaa-0052-0052-0052-000000000052';

-- === VERIFICATION QUERIES ===

SELECT 'Day 2 Summary' as info;

SELECT team, count(*) as user_count, sum(season_points) as total_points
FROM public.users WHERE id::text LIKE 'aaaaaaaa-%' GROUP BY team ORDER BY total_points DESC;

SELECT team, count(*) as hex_count
FROM (SELECT last_runner_team as team FROM public.hexes WHERE last_runner_team IS NOT NULL) t
GROUP BY team ORDER BY hex_count DESC;

SELECT u.name, u.team, u.season_points, u.total_distance_km, u.total_runs,
       CASE WHEN u.avg_cv IS NOT NULL THEN (100 - u.avg_cv)::INTEGER ELSE NULL END as stability
FROM public.users u
WHERE u.id::text LIKE 'aaaaaaaa-%' AND u.season_points > 0
ORDER BY u.season_points DESC LIMIT 15;

SELECT count(*) as total_runs_today
FROM public.run_history WHERE run_date = '2026-01-16';


-- === DAY 2 STATS ===
-- Runs today: 47
-- Flips today: 176
-- Points earned today: 321
-- Cumulative Points: Red 256 | Blue 250 | Purple 46
-- Hex Control: Red 63 | Blue 57 | Purple 36
-- Team sizes: Red 40 | Blue 40 | Purple 20