-- RunStrict Day 1 / 40 (2026-02-11)
-- Generated by simulate_day.py

-- === CREATE 100 SIMULATION AUTH ENTRIES ===
INSERT INTO auth.users (id, instance_id, aud, role, encrypted_password, email_confirmed_at, created_at, updated_at, confirmation_token, email, raw_app_meta_data, raw_user_meta_data) VALUES
  ('aaaaaaaa-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_alexrunner@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0001-0001-0001-000000000001', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_jordandash@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0002-0002-0002-000000000002', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_caseyswift@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0003-0003-0003-000000000003', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_rileyflash@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0004-0004-0004-000000000004', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_morganbolt@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0005-0005-0005-000000000005', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_taylorstride@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0006-0006-0006-000000000006', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_quinnpace@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0007-0007-0007-000000000007', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_averysprint@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0008-0008-0008-000000000008', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_blakeblaze@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0009-0009-0009-000000000009', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_cameronstorm@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0010-0010-0010-000000000010', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_dakotawind@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0011-0011-0011-000000000011', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_emeryfire@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0012-0012-0012-000000000012', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_finleywave@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0013-0013-0013-000000000013', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_graytide@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0014-0014-0014-000000000014', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_harperfrost@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0015-0015-0015-000000000015', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_indigothunder@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0016-0016-0016-000000000016', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_jamieshadow@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0017-0017-0017-000000000017', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_kainight@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0018-0018-0018-000000000018', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_logandawn@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0019-0019-0019-000000000019', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_masonstar@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0020-0020-0020-000000000020', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_noahmoon@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0021-0021-0021-000000000021', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_oliversun@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0022-0022-0022-000000000022', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_parkersky@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0023-0023-0023-000000000023', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_reesecloud@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0024-0024-0024-000000000024', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_sagestone@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0025-0025-0025-000000000025', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_skylersteel@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0026-0026-0026-000000000026', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_tatumiron@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0027-0027-0027-000000000027', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_rivergold@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0028-0028-0028-000000000028', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_wintersilver@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0029-0029-0029-000000000029', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_phoenixbronze@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0030-0030-0030-000000000030', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_stormcopper@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0031-0031-0031-000000000031', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_arrowchrome@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0032-0032-0032-000000000032', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_blazerunner@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0033-0033-0033-000000000033', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_clouddash@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0034-0034-0034-000000000034', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_dawnswift@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0035-0035-0035-000000000035', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_echoflash@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0036-0036-0036-000000000036', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_falconbolt@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0037-0037-0037-000000000037', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_galaxystride@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0038-0038-0038-000000000038', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_hawkpace@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0039-0039-0039-000000000039', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_ionsprint@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0040-0040-0040-000000000040', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_jadeblaze@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0041-0041-0041-000000000041', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_knightstorm@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0042-0042-0042-000000000042', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_lunawind@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0043-0043-0043-000000000043', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_midnightfire@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0044-0044-0044-000000000044', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_novawave@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0045-0045-0045-000000000045', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_oriontide@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0046-0046-0046-000000000046', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_pulsefrost@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0047-0047-0047-000000000047', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_quantumthunder@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0048-0048-0048-000000000048', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_ravenshadow@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0049-0049-0049-000000000049', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_shadownight@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0050-0050-0050-000000000050', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_thunderdawn@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0051-0051-0051-000000000051', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_ultrastar@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0052-0052-0052-000000000052', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_vegamoon@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0053-0053-0053-000000000053', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_wolfsun@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0054-0054-0054-000000000054', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_xenonsky@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0055-0055-0055-000000000055', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_zencloud@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0056-0056-0056-000000000056', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_acestone@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0057-0057-0057-000000000057', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_boltsteel@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0058-0058-0058-000000000058', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_cinderiron@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0059-0059-0059-000000000059', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_drakegold@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0060-0060-0060-000000000060', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_embersilver@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0061-0061-0061-000000000061', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_flintbronze@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0062-0062-0062-000000000062', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_galecopper@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0063-0063-0063-000000000063', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_havenchrome@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0064-0064-0064-000000000064', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_ivyrunner@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0065-0065-0065-000000000065', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_jinxdash@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0066-0066-0066-000000000066', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_kodaswift@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0067-0067-0067-000000000067', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_lynxflash@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0068-0068-0068-000000000068', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_mistbolt@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0069-0069-0069-000000000069', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_nyxstride@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0070-0070-0070-000000000070', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_opalpace@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0071-0071-0071-000000000071', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_paxsprint@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0072-0072-0072-000000000072', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_rainblaze@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0073-0073-0073-000000000073', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_slatestorm@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0074-0074-0074-000000000074', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_trekwind@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0075-0075-0075-000000000075', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_valefire@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0076-0076-0076-000000000076', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_wrenwave@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0077-0077-0077-000000000077', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_xylatide@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0078-0078-0078-000000000078', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_yarafrost@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0079-0079-0079-000000000079', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_zephyrthunder@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0080-0080-0080-000000000080', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_atlasshadow@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0081-0081-0081-000000000081', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_birchnight@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0082-0082-0082-000000000082', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_coraldawn@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0083-0083-0083-000000000083', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_duskstar@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0084-0084-0084-000000000084', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_elmmoon@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0085-0085-0085-000000000085', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_fernsun@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0086-0086-0086-000000000086', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_grovesky@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0087-0087-0087-000000000087', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_hazecloud@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0088-0088-0088-000000000088', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_islestone@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0089-0089-0089-000000000089', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_jetsteel@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0090-0090-0090-000000000090', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_kiteiron@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0091-0091-0091-000000000091', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_larkgold@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0092-0092-0092-000000000092', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_mosssilver@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0093-0093-0093-000000000093', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_nebulabronze@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0094-0094-0094-000000000094', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_onyxcopper@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0095-0095-0095-000000000095', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_pinechrome@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0096-0096-0096-000000000096', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_alexrunner1@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0097-0097-0097-000000000097', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_jordandash1@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0098-0098-0098-000000000098', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_caseyswift1@runstrict.test', '{"provider":"email","providers":["email"]}', '{}'),
  ('aaaaaaaa-0099-0099-0099-000000000099', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', '$2a$10$SimulatedPasswordHashForTestingOnly000000000000000000000', now(), now(), now(), '', 'sim_aaaaaaaa_rileyflash1@runstrict.test', '{"provider":"email","providers":["email"]}', '{}')
ON CONFLICT (id) DO NOTHING;

-- === CREATE 100 SIMULATION USERS ===
INSERT INTO public.users (id, name, team, avatar, season_points, home_hex, season_home_hex, home_hex_end, total_distance_km, total_runs) VALUES
  ('aaaaaaaa-0000-0000-0000-000000000000', 'AlexRunner', 'red', '🏃', 0, '89283082803ffff', '89283082803ffff', '89283082803ffff', 0, 0),
  ('aaaaaaaa-0001-0001-0001-000000000001', 'JordanDash', 'red', '🏃‍♂️', 0, '89283082807ffff', '89283082807ffff', '89283082807ffff', 0, 0),
  ('aaaaaaaa-0002-0002-0002-000000000002', 'CaseySwift', 'red', '🏃‍♀️', 0, '8928308280bffff', '8928308280bffff', '8928308280bffff', 0, 0),
  ('aaaaaaaa-0003-0003-0003-000000000003', 'RileyFlash', 'red', '🦊', 0, '8928308280fffff', '8928308280fffff', '8928308280fffff', 0, 0),
  ('aaaaaaaa-0004-0004-0004-000000000004', 'MorganBolt', 'red', '🐺', 0, '89283082813ffff', '89283082813ffff', '89283082813ffff', 0, 0),
  ('aaaaaaaa-0005-0005-0005-000000000005', 'TaylorStride', 'red', '🦅', 0, '89283082817ffff', '89283082817ffff', '89283082817ffff', 0, 0),
  ('aaaaaaaa-0006-0006-0006-000000000006', 'QuinnPace', 'red', '🐬', 0, '8928308281bffff', '8928308281bffff', '8928308281bffff', 0, 0),
  ('aaaaaaaa-0007-0007-0007-000000000007', 'AverySprint', 'red', '🔥', 0, '8928308281fffff', '8928308281fffff', '8928308281fffff', 0, 0),
  ('aaaaaaaa-0008-0008-0008-000000000008', 'BlakeBlaze', 'red', '💨', 0, '89283082823ffff', '89283082823ffff', '89283082823ffff', 0, 0),
  ('aaaaaaaa-0009-0009-0009-000000000009', 'CameronStorm', 'red', '⚡', 0, '89283082827ffff', '89283082827ffff', '89283082827ffff', 0, 0),
  ('aaaaaaaa-0010-0010-0010-000000000010', 'DakotaWind', 'red', '🌊', 0, '8928308282bffff', '8928308282bffff', '8928308282bffff', 0, 0),
  ('aaaaaaaa-0011-0011-0011-000000000011', 'EmeryFire', 'red', '🌪️', 0, '8928308282fffff', '8928308282fffff', '8928308282fffff', 0, 0),
  ('aaaaaaaa-0012-0012-0012-000000000012', 'FinleyWave', 'red', '💎', 0, '89283082833ffff', '89283082833ffff', '89283082833ffff', 0, 0),
  ('aaaaaaaa-0013-0013-0013-000000000013', 'GrayTide', 'red', '🚀', 0, '89283082837ffff', '89283082837ffff', '89283082837ffff', 0, 0),
  ('aaaaaaaa-0014-0014-0014-000000000014', 'HarperFrost', 'red', '🌟', 0, '8928308283bffff', '8928308283bffff', '8928308283bffff', 0, 0),
  ('aaaaaaaa-0015-0015-0015-000000000015', 'IndigoThunder', 'red', '✨', 0, '8928308283fffff', '8928308283fffff', '8928308283fffff', 0, 0),
  ('aaaaaaaa-0016-0016-0016-000000000016', 'JamieShadow', 'red', '🏃', 0, '89283082843ffff', '89283082843ffff', '89283082843ffff', 0, 0),
  ('aaaaaaaa-0017-0017-0017-000000000017', 'KaiNight', 'red', '🏃‍♂️', 0, '89283082847ffff', '89283082847ffff', '89283082847ffff', 0, 0),
  ('aaaaaaaa-0018-0018-0018-000000000018', 'LoganDawn', 'red', '🏃‍♀️', 0, '8928308284bffff', '8928308284bffff', '8928308284bffff', 0, 0),
  ('aaaaaaaa-0019-0019-0019-000000000019', 'MasonStar', 'red', '🦊', 0, '8928308284fffff', '8928308284fffff', '8928308284fffff', 0, 0),
  ('aaaaaaaa-0020-0020-0020-000000000020', 'NoahMoon', 'red', '🐺', 0, '89283082853ffff', '89283082853ffff', '89283082853ffff', 0, 0),
  ('aaaaaaaa-0021-0021-0021-000000000021', 'OliverSun', 'red', '🦅', 0, '89283082857ffff', '89283082857ffff', '89283082857ffff', 0, 0),
  ('aaaaaaaa-0022-0022-0022-000000000022', 'ParkerSky', 'red', '🐬', 0, '8928308285bffff', '8928308285bffff', '8928308285bffff', 0, 0),
  ('aaaaaaaa-0023-0023-0023-000000000023', 'ReeseCloud', 'red', '🔥', 0, '8928308285fffff', '8928308285fffff', '8928308285fffff', 0, 0),
  ('aaaaaaaa-0024-0024-0024-000000000024', 'SageStone', 'red', '💨', 0, '89283082863ffff', '89283082863ffff', '89283082863ffff', 0, 0),
  ('aaaaaaaa-0025-0025-0025-000000000025', 'SkylerSteel', 'red', '⚡', 0, '89283082867ffff', '89283082867ffff', '89283082867ffff', 0, 0),
  ('aaaaaaaa-0026-0026-0026-000000000026', 'TatumIron', 'red', '🌊', 0, '8928308286bffff', '8928308286bffff', '8928308286bffff', 0, 0),
  ('aaaaaaaa-0027-0027-0027-000000000027', 'RiverGold', 'red', '🌪️', 0, '8928308286fffff', '8928308286fffff', '8928308286fffff', 0, 0),
  ('aaaaaaaa-0028-0028-0028-000000000028', 'WinterSilver', 'red', '💎', 0, '89283082873ffff', '89283082873ffff', '89283082873ffff', 0, 0),
  ('aaaaaaaa-0029-0029-0029-000000000029', 'PhoenixBronze', 'red', '🚀', 0, '89283082877ffff', '89283082877ffff', '89283082877ffff', 0, 0),
  ('aaaaaaaa-0030-0030-0030-000000000030', 'StormCopper', 'red', '🌟', 0, '8928308287bffff', '8928308287bffff', '8928308287bffff', 0, 0),
  ('aaaaaaaa-0031-0031-0031-000000000031', 'ArrowChrome', 'red', '✨', 0, '8928308287fffff', '8928308287fffff', '8928308287fffff', 0, 0),
  ('aaaaaaaa-0032-0032-0032-000000000032', 'BlazeRunner', 'red', '🏃', 0, '89283082883ffff', '89283082883ffff', '89283082883ffff', 0, 0),
  ('aaaaaaaa-0033-0033-0033-000000000033', 'CloudDash', 'red', '🏃‍♂️', 0, '89283082887ffff', '89283082887ffff', '89283082887ffff', 0, 0),
  ('aaaaaaaa-0034-0034-0034-000000000034', 'DawnSwift', 'red', '🏃‍♀️', 0, '8928308288bffff', '8928308288bffff', '8928308288bffff', 0, 0),
  ('aaaaaaaa-0035-0035-0035-000000000035', 'EchoFlash', 'red', '🦊', 0, '8928308288fffff', '8928308288fffff', '8928308288fffff', 0, 0),
  ('aaaaaaaa-0036-0036-0036-000000000036', 'FalconBolt', 'red', '🐺', 0, '89283082893ffff', '89283082893ffff', '89283082893ffff', 0, 0),
  ('aaaaaaaa-0037-0037-0037-000000000037', 'GalaxyStride', 'red', '🦅', 0, '89283082897ffff', '89283082897ffff', '89283082897ffff', 0, 0),
  ('aaaaaaaa-0038-0038-0038-000000000038', 'HawkPace', 'red', '🐬', 0, '8928308289bffff', '8928308289bffff', '8928308289bffff', 0, 0),
  ('aaaaaaaa-0039-0039-0039-000000000039', 'IonSprint', 'red', '🔥', 0, '8928308289fffff', '8928308289fffff', '8928308289fffff', 0, 0),
  ('aaaaaaaa-0040-0040-0040-000000000040', 'JadeBlaze', 'blue', '💨', 0, '892830828a3ffff', '892830828a3ffff', '892830828a3ffff', 0, 0),
  ('aaaaaaaa-0041-0041-0041-000000000041', 'KnightStorm', 'blue', '⚡', 0, '892830828a7ffff', '892830828a7ffff', '892830828a7ffff', 0, 0),
  ('aaaaaaaa-0042-0042-0042-000000000042', 'LunaWind', 'blue', '🌊', 0, '892830828abffff', '892830828abffff', '892830828abffff', 0, 0),
  ('aaaaaaaa-0043-0043-0043-000000000043', 'MidnightFire', 'blue', '🌪️', 0, '892830828afffff', '892830828afffff', '892830828afffff', 0, 0),
  ('aaaaaaaa-0044-0044-0044-000000000044', 'NovaWave', 'blue', '💎', 0, '892830828b3ffff', '892830828b3ffff', '892830828b3ffff', 0, 0),
  ('aaaaaaaa-0045-0045-0045-000000000045', 'OrionTide', 'blue', '🚀', 0, '892830828b7ffff', '892830828b7ffff', '892830828b7ffff', 0, 0),
  ('aaaaaaaa-0046-0046-0046-000000000046', 'PulseFrost', 'blue', '🌟', 0, '892830828bbffff', '892830828bbffff', '892830828bbffff', 0, 0),
  ('aaaaaaaa-0047-0047-0047-000000000047', 'QuantumThunder', 'blue', '✨', 0, '892830828bfffff', '892830828bfffff', '892830828bfffff', 0, 0),
  ('aaaaaaaa-0048-0048-0048-000000000048', 'RavenShadow', 'blue', '🏃', 0, '892830828c3ffff', '892830828c3ffff', '892830828c3ffff', 0, 0),
  ('aaaaaaaa-0049-0049-0049-000000000049', 'ShadowNight', 'blue', '🏃‍♂️', 0, '892830828c7ffff', '892830828c7ffff', '892830828c7ffff', 0, 0),
  ('aaaaaaaa-0050-0050-0050-000000000050', 'ThunderDawn', 'blue', '🏃‍♀️', 0, '892830828cbffff', '892830828cbffff', '892830828cbffff', 0, 0),
  ('aaaaaaaa-0051-0051-0051-000000000051', 'UltraStar', 'blue', '🦊', 0, '892830828cfffff', '892830828cfffff', '892830828cfffff', 0, 0),
  ('aaaaaaaa-0052-0052-0052-000000000052', 'VegaMoon', 'blue', '🐺', 0, '892830828d3ffff', '892830828d3ffff', '892830828d3ffff', 0, 0),
  ('aaaaaaaa-0053-0053-0053-000000000053', 'WolfSun', 'blue', '🦅', 0, '892830828d7ffff', '892830828d7ffff', '892830828d7ffff', 0, 0),
  ('aaaaaaaa-0054-0054-0054-000000000054', 'XenonSky', 'blue', '🐬', 0, '892830828dbffff', '892830828dbffff', '892830828dbffff', 0, 0),
  ('aaaaaaaa-0055-0055-0055-000000000055', 'ZenCloud', 'blue', '🔥', 0, '892830828dfffff', '892830828dfffff', '892830828dfffff', 0, 0),
  ('aaaaaaaa-0056-0056-0056-000000000056', 'AceStone', 'blue', '💨', 0, '892830828e3ffff', '892830828e3ffff', '892830828e3ffff', 0, 0),
  ('aaaaaaaa-0057-0057-0057-000000000057', 'BoltSteel', 'blue', '⚡', 0, '892830828e7ffff', '892830828e7ffff', '892830828e7ffff', 0, 0),
  ('aaaaaaaa-0058-0058-0058-000000000058', 'CinderIron', 'blue', '🌊', 0, '892830828ebffff', '892830828ebffff', '892830828ebffff', 0, 0),
  ('aaaaaaaa-0059-0059-0059-000000000059', 'DrakeGold', 'blue', '🌪️', 0, '892830828efffff', '892830828efffff', '892830828efffff', 0, 0),
  ('aaaaaaaa-0060-0060-0060-000000000060', 'EmberSilver', 'blue', '💎', 0, '892830828f3ffff', '892830828f3ffff', '892830828f3ffff', 0, 0),
  ('aaaaaaaa-0061-0061-0061-000000000061', 'FlintBronze', 'blue', '🚀', 0, '892830828f7ffff', '892830828f7ffff', '892830828f7ffff', 0, 0),
  ('aaaaaaaa-0062-0062-0062-000000000062', 'GaleCopper', 'blue', '🌟', 0, '892830828fbffff', '892830828fbffff', '892830828fbffff', 0, 0),
  ('aaaaaaaa-0063-0063-0063-000000000063', 'HavenChrome', 'blue', '✨', 0, '892830828ffffff', '892830828ffffff', '892830828ffffff', 0, 0),
  ('aaaaaaaa-0064-0064-0064-000000000064', 'IvyRunner', 'blue', '🏃', 0, '89283082903ffff', '89283082903ffff', '89283082903ffff', 0, 0),
  ('aaaaaaaa-0065-0065-0065-000000000065', 'JinxDash', 'blue', '🏃‍♂️', 0, '89283082907ffff', '89283082907ffff', '89283082907ffff', 0, 0),
  ('aaaaaaaa-0066-0066-0066-000000000066', 'KodaSwift', 'blue', '🏃‍♀️', 0, '8928308290bffff', '8928308290bffff', '8928308290bffff', 0, 0),
  ('aaaaaaaa-0067-0067-0067-000000000067', 'LynxFlash', 'blue', '🦊', 0, '8928308290fffff', '8928308290fffff', '8928308290fffff', 0, 0),
  ('aaaaaaaa-0068-0068-0068-000000000068', 'MistBolt', 'blue', '🐺', 0, '89283082913ffff', '89283082913ffff', '89283082913ffff', 0, 0),
  ('aaaaaaaa-0069-0069-0069-000000000069', 'NyxStride', 'blue', '🦅', 0, '89283082917ffff', '89283082917ffff', '89283082917ffff', 0, 0),
  ('aaaaaaaa-0070-0070-0070-000000000070', 'OpalPace', 'blue', '🐬', 0, '8928308291bffff', '8928308291bffff', '8928308291bffff', 0, 0),
  ('aaaaaaaa-0071-0071-0071-000000000071', 'PaxSprint', 'blue', '🔥', 0, '8928308291fffff', '8928308291fffff', '8928308291fffff', 0, 0),
  ('aaaaaaaa-0072-0072-0072-000000000072', 'RainBlaze', 'blue', '💨', 0, '89283082923ffff', '89283082923ffff', '89283082923ffff', 0, 0),
  ('aaaaaaaa-0073-0073-0073-000000000073', 'SlateStorm', 'blue', '⚡', 0, '89283082927ffff', '89283082927ffff', '89283082927ffff', 0, 0),
  ('aaaaaaaa-0074-0074-0074-000000000074', 'TrekWind', 'blue', '🌊', 0, '8928308292bffff', '8928308292bffff', '8928308292bffff', 0, 0),
  ('aaaaaaaa-0075-0075-0075-000000000075', 'ValeFire', 'blue', '🌪️', 0, '8928308292fffff', '8928308292fffff', '8928308292fffff', 0, 0),
  ('aaaaaaaa-0076-0076-0076-000000000076', 'WrenWave', 'blue', '💎', 0, '89283082933ffff', '89283082933ffff', '89283082933ffff', 0, 0),
  ('aaaaaaaa-0077-0077-0077-000000000077', 'XylaTide', 'blue', '🚀', 0, '89283082937ffff', '89283082937ffff', '89283082937ffff', 0, 0),
  ('aaaaaaaa-0078-0078-0078-000000000078', 'YaraFrost', 'blue', '🌟', 0, '8928308293bffff', '8928308293bffff', '8928308293bffff', 0, 0),
  ('aaaaaaaa-0079-0079-0079-000000000079', 'ZephyrThunder', 'blue', '✨', 0, '8928308293fffff', '8928308293fffff', '8928308293fffff', 0, 0),
  ('aaaaaaaa-0080-0080-0080-000000000080', 'AtlasShadow', 'purple', '🏃', 0, '89283082943ffff', '89283082943ffff', '89283082943ffff', 0, 0),
  ('aaaaaaaa-0081-0081-0081-000000000081', 'BirchNight', 'purple', '🏃‍♂️', 0, '89283082947ffff', '89283082947ffff', '89283082947ffff', 0, 0),
  ('aaaaaaaa-0082-0082-0082-000000000082', 'CoralDawn', 'purple', '🏃‍♀️', 0, '8928308294bffff', '8928308294bffff', '8928308294bffff', 0, 0),
  ('aaaaaaaa-0083-0083-0083-000000000083', 'DuskStar', 'purple', '🦊', 0, '8928308294fffff', '8928308294fffff', '8928308294fffff', 0, 0),
  ('aaaaaaaa-0084-0084-0084-000000000084', 'ElmMoon', 'purple', '🐺', 0, '89283082953ffff', '89283082953ffff', '89283082953ffff', 0, 0),
  ('aaaaaaaa-0085-0085-0085-000000000085', 'FernSun', 'purple', '🦅', 0, '89283082957ffff', '89283082957ffff', '89283082957ffff', 0, 0),
  ('aaaaaaaa-0086-0086-0086-000000000086', 'GroveSky', 'purple', '🐬', 0, '8928308295bffff', '8928308295bffff', '8928308295bffff', 0, 0),
  ('aaaaaaaa-0087-0087-0087-000000000087', 'HazeCloud', 'purple', '🔥', 0, '8928308295fffff', '8928308295fffff', '8928308295fffff', 0, 0),
  ('aaaaaaaa-0088-0088-0088-000000000088', 'IsleStone', 'purple', '💨', 0, '89283082963ffff', '89283082963ffff', '89283082963ffff', 0, 0),
  ('aaaaaaaa-0089-0089-0089-000000000089', 'JetSteel', 'purple', '⚡', 0, '89283082967ffff', '89283082967ffff', '89283082967ffff', 0, 0),
  ('aaaaaaaa-0090-0090-0090-000000000090', 'KiteIron', 'purple', '🌊', 0, '8928308296bffff', '8928308296bffff', '8928308296bffff', 0, 0),
  ('aaaaaaaa-0091-0091-0091-000000000091', 'LarkGold', 'purple', '🌪️', 0, '8928308296fffff', '8928308296fffff', '8928308296fffff', 0, 0),
  ('aaaaaaaa-0092-0092-0092-000000000092', 'MossSilver', 'purple', '💎', 0, '89283082973ffff', '89283082973ffff', '89283082973ffff', 0, 0),
  ('aaaaaaaa-0093-0093-0093-000000000093', 'NebulaBronze', 'purple', '🚀', 0, '89283082977ffff', '89283082977ffff', '89283082977ffff', 0, 0),
  ('aaaaaaaa-0094-0094-0094-000000000094', 'OnyxCopper', 'purple', '🌟', 0, '8928308297bffff', '8928308297bffff', '8928308297bffff', 0, 0),
  ('aaaaaaaa-0095-0095-0095-000000000095', 'PineChrome', 'purple', '✨', 0, '8928308297fffff', '8928308297fffff', '8928308297fffff', 0, 0),
  ('aaaaaaaa-0096-0096-0096-000000000096', 'AlexRunner1', 'purple', '🏃', 0, '89283082983ffff', '89283082983ffff', '89283082983ffff', 0, 0),
  ('aaaaaaaa-0097-0097-0097-000000000097', 'JordanDash1', 'purple', '🏃‍♂️', 0, '89283082987ffff', '89283082987ffff', '89283082987ffff', 0, 0),
  ('aaaaaaaa-0098-0098-0098-000000000098', 'CaseySwift1', 'purple', '🏃‍♀️', 0, '8928308298bffff', '8928308298bffff', '8928308298bffff', 0, 0),
  ('aaaaaaaa-0099-0099-0099-000000000099', 'RileyFlash1', 'purple', '🦊', 0, '8928308298fffff', '8928308298fffff', '8928308298fffff', 0, 0)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, team = EXCLUDED.team, avatar = EXCLUDED.avatar,
  season_points = 0, home_hex = EXCLUDED.home_hex,
  season_home_hex = EXCLUDED.season_home_hex, home_hex_end = EXCLUDED.home_hex_end,
  total_distance_km = 0, total_runs = 0;

-- === DAY 1 RUNS (45 runs) ===
INSERT INTO public.run_history (id, user_id, run_date, start_time, end_time, distance_km, duration_seconds, avg_pace_min_per_km, flip_count, flip_points, team_at_run, cv) VALUES
  ('323f2221-3126-41e5-bade-98b373aae29a', 'aaaaaaaa-0000-0000-0000-000000000000', '2026-02-11', '2026-02-11 16:00:00+00', '2026-02-11 16:51:11+00', 9.36, 3071, 5.47, 18, 18, 'red', 7.6),
  ('fd515e95-b257-48a1-a0c1-eb8de312be99', 'aaaaaaaa-0001-0001-0001-000000000001', '2026-02-11', '2026-02-11 17:54:00+00', '2026-02-11 19:09:25+00', 13.74, 4525, 5.49, 23, 23, 'red', 5.2),
  ('cb8a2a0c-e652-4052-bc65-1dfee5f610a1', 'aaaaaaaa-0002-0002-0002-000000000002', '2026-02-11', '2026-02-11 19:42:00+00', '2026-02-11 20:39:09+00', 12.59, 3429, 4.54, 11, 11, 'red', 4.7),
  ('f3be83a3-b6f2-482b-b0ad-fde505fda152', 'aaaaaaaa-0003-0003-0003-000000000003', '2026-02-11', '2026-02-11 06:07:00+00', '2026-02-11 07:04:09+00', 12.32, 3429, 4.64, 9, 9, 'red', 6.7),
  ('5d108e90-ac3f-443f-800b-0f8d6bf80f9d', 'aaaaaaaa-0004-0004-0004-000000000004', '2026-02-11', '2026-02-11 09:31:00+00', '2026-02-11 10:35:20+00', 11.72, 3860, 5.49, 4, 4, 'red', 4.5),
  ('0880ea59-ecf8-41e1-8985-5b40e0b866e8', 'aaaaaaaa-0006-0006-0006-000000000006', '2026-02-11', '2026-02-11 07:12:00+00', '2026-02-11 08:19:37+00', 14.42, 4057, 4.69, 6, 6, 'red', 6.4),
  ('08db3b28-5634-4bda-af7d-8e1b04f65af9', 'aaaaaaaa-0007-0007-0007-000000000007', '2026-02-11', '2026-02-11 11:08:00+00', '2026-02-11 12:11:32+00', 11.92, 3812, 5.33, 6, 6, 'red', 3.6),
  ('4b3641b0-e013-456b-bd31-f07d656453c4', 'aaaaaaaa-0008-0008-0008-000000000008', '2026-02-11', '2026-02-11 19:24:00+00', '2026-02-11 20:20:27+00', 10.9, 3387, 5.18, 4, 4, 'red', 7.4),
  ('2ff6169c-c9c1-4c40-99eb-5dea3c723b19', 'aaaaaaaa-0009-0009-0009-000000000009', '2026-02-11', '2026-02-11 17:05:00+00', '2026-02-11 17:51:49+00', 9.92, 2809, 4.72, 4, 4, 'red', 7.2),
  ('b4bfd467-199f-4c38-aa48-eee72acdb7a0', 'aaaaaaaa-0010-0010-0010-000000000010', '2026-02-11', '2026-02-11 06:25:00+00', '2026-02-11 07:12:52+00', 8.55, 2872, 5.6, 3, 3, 'red', 14.0),
  ('17662f51-63ab-48ed-bc8b-4907325294d7', 'aaaaaaaa-0011-0011-0011-000000000011', '2026-02-11', '2026-02-11 21:36:00+00', '2026-02-11 22:06:04+00', 5.02, 1804, 5.99, 3, 3, 'red', 12.2),
  ('f4e84666-ccbf-40e2-88c1-9887ec5a1f6a', 'aaaaaaaa-0012-0012-0012-000000000012', '2026-02-11', '2026-02-11 07:04:00+00', '2026-02-11 07:47:28+00', 8.25, 2608, 5.27, 2, 2, 'red', 11.7),
  ('c48efb35-9edd-4c25-98a9-f927e870a1ae', 'aaaaaaaa-0016-0016-0016-000000000016', '2026-02-11', '2026-02-11 11:51:00+00', '2026-02-11 12:31:07+00', 6.38, 2407, 6.29, 1, 1, 'red', 7.9),
  ('7e09eb37-ad5d-47db-b427-d32b16567a82', 'aaaaaaaa-0018-0018-0018-000000000018', '2026-02-11', '2026-02-11 21:45:00+00', '2026-02-11 22:25:06+00', 6.88, 2406, 5.83, 1, 1, 'red', 10.4),
  ('54d451d4-cd44-49bc-8849-c739d3fed925', 'aaaaaaaa-0019-0019-0019-000000000019', '2026-02-11', '2026-02-11 17:32:00+00', '2026-02-11 18:33:53+00', 9.87, 3713, 6.27, 4, 4, 'red', 9.6),
  ('adadf39f-165a-4020-bf3f-d4ecb33f17a9', 'aaaaaaaa-0020-0020-0020-000000000020', '2026-02-11', '2026-02-11 06:33:00+00', '2026-02-11 07:19:13+00', 9.17, 2773, 5.04, 3, 3, 'red', 9.3),
  ('b4568f69-ba9f-42f7-8336-ce6d27e5bb91', 'aaaaaaaa-0021-0021-0021-000000000021', '2026-02-11', '2026-02-11 06:31:00+00', '2026-02-11 07:15:32+00', 7.4, 2672, 6.02, 0, 0, 'red', 6.5),
  ('23f817f4-287d-4529-9671-c294e1fbf064', 'aaaaaaaa-0022-0022-0022-000000000022', '2026-02-11', '2026-02-11 20:12:00+00', '2026-02-11 20:51:52+00', 7.82, 2392, 5.1, 2, 2, 'red', 9.1),
  ('0882ef31-6ce5-4fd6-a0a3-59349d3198dc', 'aaaaaaaa-0023-0023-0023-000000000023', '2026-02-11', '2026-02-11 21:22:00+00', '2026-02-11 21:55:00+00', 6.46, 1980, 5.11, 1, 1, 'red', 5.8),
  ('b12abf86-15e1-4a22-9a7d-1caba4ceeb41', 'aaaaaaaa-0024-0024-0024-000000000024', '2026-02-11', '2026-02-11 07:47:00+00', '2026-02-11 08:33:55+00', 9.13, 2815, 5.14, 2, 2, 'red', 8.6),
  ('44fbbafa-6f34-4490-b25c-0884ea95a4f0', 'aaaaaaaa-0026-0026-0026-000000000026', '2026-02-11', '2026-02-11 08:49:00+00', '2026-02-11 09:27:38+00', 6.44, 2318, 6.0, 4, 4, 'red', 9.0),
  ('90306e33-7684-4b86-afeb-f0dac2f77cdb', 'aaaaaaaa-0029-0029-0029-000000000029', '2026-02-11', '2026-02-11 18:50:00+00', '2026-02-11 19:25:00+00', 6.33, 2100, 5.53, 0, 0, 'red', 14.2),
  ('eb7ef9d1-1036-4a2f-a9e6-eafeb9751b8e', 'aaaaaaaa-0032-0032-0032-000000000032', '2026-02-11', '2026-02-11 14:09:00+00', '2026-02-11 14:42:27+00', 5.76, 2007, 5.81, 1, 1, 'red', 7.3),
  ('a7edafae-faf3-49a6-8cb9-036a70aed062', 'aaaaaaaa-0033-0033-0033-000000000033', '2026-02-11', '2026-02-11 19:32:00+00', '2026-02-11 20:20:11+00', 9.32, 2891, 5.17, 2, 2, 'red', 5.9),
  ('88978d86-1456-411d-b774-353f9929a077', 'aaaaaaaa-0034-0034-0034-000000000034', '2026-02-11', '2026-02-11 20:15:00+00', '2026-02-11 21:08:24+00', 9.71, 3204, 5.5, 2, 2, 'red', 14.5),
  ('ebbf8cc8-c7ca-4daa-8898-466ea6365d24', 'aaaaaaaa-0035-0035-0035-000000000035', '2026-02-11', '2026-02-11 19:48:00+00', '2026-02-11 20:34:16+00', 7.83, 2776, 5.91, 2, 2, 'red', 12.2),
  ('9ce3ca57-bcce-4900-853e-9e78136ca5ac', 'aaaaaaaa-0036-0036-0036-000000000036', '2026-02-11', '2026-02-11 06:35:00+00', '2026-02-11 07:27:22+00', 9.47, 3142, 5.53, 2, 2, 'red', 9.1),
  ('e72eabad-4042-478e-b673-1c1885a1e247', 'aaaaaaaa-0037-0037-0037-000000000037', '2026-02-11', '2026-02-11 11:54:00+00', '2026-02-11 12:46:19+00', 8.96, 3139, 5.84, 2, 2, 'red', 14.6),
  ('027708b7-4715-483f-89d4-6c80bed0c9c3', 'aaaaaaaa-0039-0039-0039-000000000039', '2026-02-11', '2026-02-11 15:11:00+00', '2026-02-11 16:06:35+00', 8.66, 3335, 6.42, 1, 1, 'red', 8.0),
  ('6a81e0e8-f11f-4e22-8ee6-7c119b874c5b', 'aaaaaaaa-0041-0041-0041-000000000041', '2026-02-11', '2026-02-11 14:15:00+00', '2026-02-11 14:46:23+00', 5.77, 1883, 5.44, 13, 13, 'blue', 5.2),
  ('8e16dabe-440f-4fb8-8f82-b9e3194be14b', 'aaaaaaaa-0042-0042-0042-000000000042', '2026-02-11', '2026-02-11 16:11:00+00', '2026-02-11 16:45:27+00', 6.54, 2067, 5.27, 11, 11, 'blue', 11.9),
  ('6ac748d5-c5d1-4a61-bf31-30dd8b04e349', 'aaaaaaaa-0043-0043-0043-000000000043', '2026-02-11', '2026-02-11 08:07:00+00', '2026-02-11 09:01:10+00', 9.26, 3250, 5.85, 15, 15, 'blue', 6.0),
  ('f9dd327e-5dcf-4a26-baec-d1c6431a5ca6', 'aaaaaaaa-0045-0045-0045-000000000045', '2026-02-11', '2026-02-11 06:37:00+00', '2026-02-11 07:26:03+00', 8.43, 2943, 5.82, 9, 9, 'blue', 6.3),
  ('337bf90e-bf51-4ae9-a95c-36a149bf4503', 'aaaaaaaa-0047-0047-0047-000000000047', '2026-02-11', '2026-02-11 16:01:00+00', '2026-02-11 16:38:44+00', 6.95, 2264, 5.43, 3, 3, 'blue', 14.5),
  ('8ffa596a-80e7-4180-a6b5-7eb2a4da00fa', 'aaaaaaaa-0048-0048-0048-000000000048', '2026-02-11', '2026-02-11 18:34:00+00', '2026-02-11 19:15:57+00', 6.9, 2517, 6.08, 4, 4, 'blue', 12.6),
  ('48552241-ea8b-451b-9aa3-2bbfce3d2d19', 'aaaaaaaa-0054-0054-0054-000000000054', '2026-02-11', '2026-02-11 13:03:00+00', '2026-02-11 13:39:56+00', 5.9, 2216, 6.26, 7, 7, 'blue', 13.5),
  ('7564d7ca-caaf-46e9-b17f-0a0c9bf09b3c', 'aaaaaaaa-0055-0055-0055-000000000055', '2026-02-11', '2026-02-11 14:56:00+00', '2026-02-11 15:34:11+00', 5.77, 2291, 6.62, 2, 2, 'blue', 18.6),
  ('c97b3972-d9d7-4009-81db-f41c29ec62e1', 'aaaaaaaa-0061-0061-0061-000000000061', '2026-02-11', '2026-02-11 09:53:00+00', '2026-02-11 10:09:47+00', 2.41, 1007, 6.97, 3, 3, 'blue', 21.5),
  ('b001686d-8622-4929-8ce7-55074e80b483', 'aaaaaaaa-0065-0065-0065-000000000065', '2026-02-11', '2026-02-11 10:58:00+00', '2026-02-11 11:35:41+00', 5.4, 2261, 6.98, 2, 2, 'blue', 10.4),
  ('1e9af057-ee80-4096-b122-a7a97bf0255a', 'aaaaaaaa-0067-0067-0067-000000000067', '2026-02-11', '2026-02-11 20:48:00+00', '2026-02-11 21:25:45+00', 5.81, 2265, 6.5, 7, 7, 'blue', 23.1),
  ('2f3a4f2b-4054-4bd7-9f75-a84c356a16a5', 'aaaaaaaa-0070-0070-0070-000000000070', '2026-02-11', '2026-02-11 18:21:00+00', '2026-02-11 18:45:46+00', 3.45, 1486, 7.18, 2, 2, 'blue', 24.8),
  ('e2c8c192-3573-4a56-a97b-0c1c8c349677', 'aaaaaaaa-0072-0072-0072-000000000072', '2026-02-11', '2026-02-11 19:19:00+00', '2026-02-11 19:35:36+00', 2.58, 996, 6.44, 1, 1, 'blue', 21.1),
  ('5ee9a79a-263f-47c4-9ad1-fe0ffadd3584', 'aaaaaaaa-0074-0074-0074-000000000074', '2026-02-11', '2026-02-11 19:24:00+00', '2026-02-11 19:43:39+00', 3.16, 1179, 6.22, 3, 3, 'blue', 21.7),
  ('2546af93-9e95-42f2-bf78-da61726c5b35', 'aaaaaaaa-0083-0083-0083-000000000083', '2026-02-11', '2026-02-11 12:23:00+00', '2026-02-11 13:00:17+00', 5.06, 2237, 7.37, 10, 10, 'purple', 22.6),
  ('5321c17f-4bd3-4b6e-9423-d3a03dee4a72', 'aaaaaaaa-0086-0086-0086-000000000086', '2026-02-11', '2026-02-11 06:36:00+00', '2026-02-11 07:00:20+00', 3.22, 1460, 7.56, 6, 6, 'purple', 15.6);

-- === HEX MAP (146 hexes) ===
INSERT INTO public.hexes (id, last_runner_team) VALUES
  ('8928308281bffff', 'red'),
  ('89283082813ffff', 'blue'),
  ('89283082a5bffff', 'blue'),
  ('8928308282bffff', 'blue'),
  ('89283082a6fffff', 'red'),
  ('89283082a4fffff', 'red'),
  ('89283082977ffff', 'blue'),
  ('89283082817ffff', 'red'),
  ('892830829b3ffff', 'red'),
  ('89283082a6bffff', 'red'),
  ('8928308282fffff', 'red'),
  ('89283082a5fffff', 'red'),
  ('89283082837ffff', 'blue'),
  ('89283082823ffff', 'red'),
  ('89283082a37ffff', 'red'),
  ('892830828dfffff', 'blue'),
  ('89283082a63ffff', 'red'),
  ('8928308297bffff', 'purple'),
  ('8928308281fffff', 'red'),
  ('89283082973ffff', 'purple'),
  ('89283082a47ffff', 'red'),
  ('89283082807ffff', 'blue'),
  ('89283082a0bffff', 'red'),
  ('8928308280bffff', 'purple'),
  ('89283082a3bffff', 'blue'),
  ('89283082843ffff', 'red'),
  ('89283082a67ffff', 'red'),
  ('8928308287bffff', 'blue'),
  ('892830829d7ffff', 'red'),
  ('8928308288fffff', 'blue'),
  ('8928308283fffff', 'red'),
  ('89283082a33ffff', 'red'),
  ('8928308283bffff', 'red'),
  ('89283082853ffff', 'red'),
  ('8928308293fffff', 'blue'),
  ('89283082a43ffff', 'red'),
  ('8928308280fffff', 'red'),
  ('89283082a53ffff', 'red'),
  ('89283082833ffff', 'red'),
  ('89283082903ffff', 'blue'),
  ('89283082947ffff', 'red'),
  ('892830829e3ffff', 'purple'),
  ('89283082a57ffff', 'red'),
  ('89283082a4bffff', 'red'),
  ('892830828cfffff', 'blue'),
  ('89283082a0fffff', 'red'),
  ('892830828f7ffff', 'blue'),
  ('892830828d3ffff', 'blue'),
  ('892830828fbffff', 'blue'),
  ('892830829c3ffff', 'blue'),
  ('89283082827ffff', 'red'),
  ('892830829dfffff', 'red'),
  ('892830829cfffff', 'blue'),
  ('892830829abffff', 'blue'),
  ('892830828a3ffff', 'blue'),
  ('89283082847ffff', 'red'),
  ('892830828c7ffff', 'blue'),
  ('89283082a13ffff', 'red'),
  ('8928308286bffff', 'red'),
  ('89283082883ffff', 'blue'),
  ('89283082873ffff', 'blue'),
  ('89283082957ffff', 'purple'),
  ('8928308284bffff', 'red'),
  ('892830828c3ffff', 'purple'),
  ('8928308298bffff', 'purple'),
  ('892830829f7ffff', 'red'),
  ('89283082803ffff', 'blue'),
  ('89283082857ffff', 'red'),
  ('8928308298fffff', 'red'),
  ('89283082a27ffff', 'red'),
  ('89283082a1fffff', 'red'),
  ('892830828bfffff', 'blue'),
  ('892830828afffff', 'blue'),
  ('892830829a3ffff', 'red'),
  ('8928308284fffff', 'red'),
  ('8928308285bffff', 'red'),
  ('892830828bbffff', 'blue'),
  ('8928308296bffff', 'red'),
  ('8928308293bffff', 'purple'),
  ('892830828b3ffff', 'blue'),
  ('8928308285fffff', 'blue'),
  ('89283082863ffff', 'red'),
  ('89283082893ffff', 'blue'),
  ('892830828e7ffff', 'blue'),
  ('892830828cbffff', 'blue'),
  ('89283082867ffff', 'red'),
  ('892830829dbffff', 'blue'),
  ('8928308291fffff', 'red'),
  ('89283082a2fffff', 'red'),
  ('89283082953ffff', 'purple'),
  ('89283082907ffff', 'blue'),
  ('89283082887ffff', 'blue'),
  ('892830829cbffff', 'red'),
  ('8928308294bffff', 'purple'),
  ('8928308286fffff', 'blue'),
  ('8928308288bffff', 'blue'),
  ('892830829fbffff', 'blue'),
  ('892830829a7ffff', 'red'),
  ('8928308295fffff', 'blue'),
  ('89283082877ffff', 'blue'),
  ('8928308287fffff', 'blue'),
  ('89283082913ffff', 'blue'),
  ('8928308292fffff', 'blue'),
  ('8928308289bffff', 'blue'),
  ('8928308292bffff', 'red'),
  ('8928308289fffff', 'blue'),
  ('89283082a17ffff', 'blue'),
  ('892830828ebffff', 'blue'),
  ('89283082967ffff', 'red'),
  ('892830829bbffff', 'blue'),
  ('89283082897ffff', 'blue'),
  ('892830828a7ffff', 'blue'),
  ('892830828abffff', 'blue'),
  ('892830828b7ffff', 'blue'),
  ('892830828e3ffff', 'blue'),
  ('89283082917ffff', 'blue'),
  ('89283082997ffff', 'red'),
  ('8928308291bffff', 'red'),
  ('89283082963ffff', 'purple'),
  ('892830829d3ffff', 'red'),
  ('8928308290bffff', 'blue'),
  ('89283082a03ffff', 'red'),
  ('8928308299fffff', 'blue'),
  ('892830828d7ffff', 'blue'),
  ('892830828dbffff', 'blue'),
  ('892830829bfffff', 'blue'),
  ('8928308295bffff', 'blue'),
  ('8928308290fffff', 'blue'),
  ('89283082993ffff', 'blue'),
  ('89283082923ffff', 'purple'),
  ('892830828efffff', 'blue'),
  ('89283082983ffff', 'purple'),
  ('892830829e7ffff', 'blue'),
  ('892830829c7ffff', 'blue'),
  ('892830829b7ffff', 'blue'),
  ('8928308299bffff', 'blue'),
  ('892830828f3ffff', 'blue'),
  ('89283082987ffff', 'blue'),
  ('89283082927ffff', 'purple'),
  ('892830828ffffff', 'blue'),
  ('89283082933ffff', 'blue'),
  ('89283082943ffff', 'blue'),
  ('8928308294fffff', 'blue'),
  ('892830829f3ffff', 'blue'),
  ('89283082937ffff', 'purple'),
  ('89283082a23ffff', 'purple')
ON CONFLICT (id) DO UPDATE SET last_runner_team = EXCLUDED.last_runner_team;

-- === UPDATE USER SEASON STATS ===
UPDATE public.users SET season_points = 23, total_distance_km = 13.74, total_runs = 1, avg_pace_min_per_km = 5.49, avg_cv = 5.2 WHERE id = 'aaaaaaaa-0001-0001-0001-000000000001';
UPDATE public.users SET season_points = 18, total_distance_km = 9.36, total_runs = 1, avg_pace_min_per_km = 5.47, avg_cv = 7.6 WHERE id = 'aaaaaaaa-0000-0000-0000-000000000000';
UPDATE public.users SET season_points = 15, total_distance_km = 9.26, total_runs = 1, avg_pace_min_per_km = 5.85, avg_cv = 6.0 WHERE id = 'aaaaaaaa-0043-0043-0043-000000000043';
UPDATE public.users SET season_points = 13, total_distance_km = 5.77, total_runs = 1, avg_pace_min_per_km = 5.44, avg_cv = 5.2 WHERE id = 'aaaaaaaa-0041-0041-0041-000000000041';
UPDATE public.users SET season_points = 11, total_distance_km = 12.59, total_runs = 1, avg_pace_min_per_km = 4.54, avg_cv = 4.7 WHERE id = 'aaaaaaaa-0002-0002-0002-000000000002';
UPDATE public.users SET season_points = 11, total_distance_km = 6.54, total_runs = 1, avg_pace_min_per_km = 5.27, avg_cv = 11.9 WHERE id = 'aaaaaaaa-0042-0042-0042-000000000042';
UPDATE public.users SET season_points = 10, total_distance_km = 5.06, total_runs = 1, avg_pace_min_per_km = 7.37, avg_cv = 22.6 WHERE id = 'aaaaaaaa-0083-0083-0083-000000000083';
UPDATE public.users SET season_points = 9, total_distance_km = 12.32, total_runs = 1, avg_pace_min_per_km = 4.64, avg_cv = 6.7 WHERE id = 'aaaaaaaa-0003-0003-0003-000000000003';
UPDATE public.users SET season_points = 9, total_distance_km = 8.43, total_runs = 1, avg_pace_min_per_km = 5.82, avg_cv = 6.3 WHERE id = 'aaaaaaaa-0045-0045-0045-000000000045';
UPDATE public.users SET season_points = 7, total_distance_km = 5.9, total_runs = 1, avg_pace_min_per_km = 6.26, avg_cv = 13.5 WHERE id = 'aaaaaaaa-0054-0054-0054-000000000054';
UPDATE public.users SET season_points = 7, total_distance_km = 5.81, total_runs = 1, avg_pace_min_per_km = 6.5, avg_cv = 23.1 WHERE id = 'aaaaaaaa-0067-0067-0067-000000000067';
UPDATE public.users SET season_points = 6, total_distance_km = 14.42, total_runs = 1, avg_pace_min_per_km = 4.69, avg_cv = 6.4 WHERE id = 'aaaaaaaa-0006-0006-0006-000000000006';
UPDATE public.users SET season_points = 6, total_distance_km = 11.92, total_runs = 1, avg_pace_min_per_km = 5.33, avg_cv = 3.6 WHERE id = 'aaaaaaaa-0007-0007-0007-000000000007';
UPDATE public.users SET season_points = 6, total_distance_km = 3.22, total_runs = 1, avg_pace_min_per_km = 7.56, avg_cv = 15.6 WHERE id = 'aaaaaaaa-0086-0086-0086-000000000086';
UPDATE public.users SET season_points = 4, total_distance_km = 11.72, total_runs = 1, avg_pace_min_per_km = 5.49, avg_cv = 4.5 WHERE id = 'aaaaaaaa-0004-0004-0004-000000000004';
UPDATE public.users SET season_points = 4, total_distance_km = 10.9, total_runs = 1, avg_pace_min_per_km = 5.18, avg_cv = 7.4 WHERE id = 'aaaaaaaa-0008-0008-0008-000000000008';
UPDATE public.users SET season_points = 4, total_distance_km = 9.92, total_runs = 1, avg_pace_min_per_km = 4.72, avg_cv = 7.2 WHERE id = 'aaaaaaaa-0009-0009-0009-000000000009';
UPDATE public.users SET season_points = 4, total_distance_km = 9.87, total_runs = 1, avg_pace_min_per_km = 6.27, avg_cv = 9.6 WHERE id = 'aaaaaaaa-0019-0019-0019-000000000019';
UPDATE public.users SET season_points = 4, total_distance_km = 6.44, total_runs = 1, avg_pace_min_per_km = 6.0, avg_cv = 9.0 WHERE id = 'aaaaaaaa-0026-0026-0026-000000000026';
UPDATE public.users SET season_points = 4, total_distance_km = 6.9, total_runs = 1, avg_pace_min_per_km = 6.08, avg_cv = 12.6 WHERE id = 'aaaaaaaa-0048-0048-0048-000000000048';
UPDATE public.users SET season_points = 3, total_distance_km = 8.55, total_runs = 1, avg_pace_min_per_km = 5.6, avg_cv = 14.0 WHERE id = 'aaaaaaaa-0010-0010-0010-000000000010';
UPDATE public.users SET season_points = 3, total_distance_km = 5.02, total_runs = 1, avg_pace_min_per_km = 5.99, avg_cv = 12.2 WHERE id = 'aaaaaaaa-0011-0011-0011-000000000011';
UPDATE public.users SET season_points = 3, total_distance_km = 9.17, total_runs = 1, avg_pace_min_per_km = 5.04, avg_cv = 9.3 WHERE id = 'aaaaaaaa-0020-0020-0020-000000000020';
UPDATE public.users SET season_points = 3, total_distance_km = 6.95, total_runs = 1, avg_pace_min_per_km = 5.43, avg_cv = 14.5 WHERE id = 'aaaaaaaa-0047-0047-0047-000000000047';
UPDATE public.users SET season_points = 3, total_distance_km = 2.41, total_runs = 1, avg_pace_min_per_km = 6.97, avg_cv = 21.5 WHERE id = 'aaaaaaaa-0061-0061-0061-000000000061';
UPDATE public.users SET season_points = 3, total_distance_km = 3.16, total_runs = 1, avg_pace_min_per_km = 6.22, avg_cv = 21.7 WHERE id = 'aaaaaaaa-0074-0074-0074-000000000074';
UPDATE public.users SET season_points = 2, total_distance_km = 8.25, total_runs = 1, avg_pace_min_per_km = 5.27, avg_cv = 11.7 WHERE id = 'aaaaaaaa-0012-0012-0012-000000000012';
UPDATE public.users SET season_points = 2, total_distance_km = 7.82, total_runs = 1, avg_pace_min_per_km = 5.1, avg_cv = 9.1 WHERE id = 'aaaaaaaa-0022-0022-0022-000000000022';
UPDATE public.users SET season_points = 2, total_distance_km = 9.13, total_runs = 1, avg_pace_min_per_km = 5.14, avg_cv = 8.6 WHERE id = 'aaaaaaaa-0024-0024-0024-000000000024';
UPDATE public.users SET season_points = 2, total_distance_km = 9.32, total_runs = 1, avg_pace_min_per_km = 5.17, avg_cv = 5.9 WHERE id = 'aaaaaaaa-0033-0033-0033-000000000033';
UPDATE public.users SET season_points = 2, total_distance_km = 9.71, total_runs = 1, avg_pace_min_per_km = 5.5, avg_cv = 14.5 WHERE id = 'aaaaaaaa-0034-0034-0034-000000000034';
UPDATE public.users SET season_points = 2, total_distance_km = 7.83, total_runs = 1, avg_pace_min_per_km = 5.91, avg_cv = 12.2 WHERE id = 'aaaaaaaa-0035-0035-0035-000000000035';
UPDATE public.users SET season_points = 2, total_distance_km = 9.47, total_runs = 1, avg_pace_min_per_km = 5.53, avg_cv = 9.1 WHERE id = 'aaaaaaaa-0036-0036-0036-000000000036';
UPDATE public.users SET season_points = 2, total_distance_km = 8.96, total_runs = 1, avg_pace_min_per_km = 5.84, avg_cv = 14.6 WHERE id = 'aaaaaaaa-0037-0037-0037-000000000037';
UPDATE public.users SET season_points = 2, total_distance_km = 5.77, total_runs = 1, avg_pace_min_per_km = 6.62, avg_cv = 18.6 WHERE id = 'aaaaaaaa-0055-0055-0055-000000000055';
UPDATE public.users SET season_points = 2, total_distance_km = 5.4, total_runs = 1, avg_pace_min_per_km = 6.98, avg_cv = 10.4 WHERE id = 'aaaaaaaa-0065-0065-0065-000000000065';
UPDATE public.users SET season_points = 2, total_distance_km = 3.45, total_runs = 1, avg_pace_min_per_km = 7.18, avg_cv = 24.8 WHERE id = 'aaaaaaaa-0070-0070-0070-000000000070';
UPDATE public.users SET season_points = 1, total_distance_km = 6.38, total_runs = 1, avg_pace_min_per_km = 6.29, avg_cv = 7.9 WHERE id = 'aaaaaaaa-0016-0016-0016-000000000016';
UPDATE public.users SET season_points = 1, total_distance_km = 6.88, total_runs = 1, avg_pace_min_per_km = 5.83, avg_cv = 10.4 WHERE id = 'aaaaaaaa-0018-0018-0018-000000000018';
UPDATE public.users SET season_points = 1, total_distance_km = 6.46, total_runs = 1, avg_pace_min_per_km = 5.11, avg_cv = 5.8 WHERE id = 'aaaaaaaa-0023-0023-0023-000000000023';
UPDATE public.users SET season_points = 1, total_distance_km = 5.76, total_runs = 1, avg_pace_min_per_km = 5.81, avg_cv = 7.3 WHERE id = 'aaaaaaaa-0032-0032-0032-000000000032';
UPDATE public.users SET season_points = 1, total_distance_km = 8.66, total_runs = 1, avg_pace_min_per_km = 6.42, avg_cv = 8.0 WHERE id = 'aaaaaaaa-0039-0039-0039-000000000039';
UPDATE public.users SET season_points = 1, total_distance_km = 2.58, total_runs = 1, avg_pace_min_per_km = 6.44, avg_cv = 21.1 WHERE id = 'aaaaaaaa-0072-0072-0072-000000000072';
UPDATE public.users SET season_points = 0, total_distance_km = 7.4, total_runs = 1, avg_pace_min_per_km = 6.02, avg_cv = 6.5 WHERE id = 'aaaaaaaa-0021-0021-0021-000000000021';
UPDATE public.users SET season_points = 0, total_distance_km = 6.33, total_runs = 1, avg_pace_min_per_km = 5.53, avg_cv = 14.2 WHERE id = 'aaaaaaaa-0029-0029-0029-000000000029';

-- === VERIFICATION QUERIES ===

SELECT 'Day 1 Summary' as info;

SELECT team, count(*) as user_count, sum(season_points) as total_points
FROM public.users WHERE id::text LIKE 'aaaaaaaa-%' GROUP BY team ORDER BY total_points DESC;

SELECT team, count(*) as hex_count
FROM (SELECT last_runner_team as team FROM public.hexes WHERE last_runner_team IS NOT NULL) t
GROUP BY team ORDER BY hex_count DESC;

SELECT u.name, u.team, u.season_points, u.total_distance_km, u.total_runs,
       CASE WHEN u.avg_cv IS NOT NULL THEN (100 - u.avg_cv)::INTEGER ELSE NULL END as stability
FROM public.users u
WHERE u.id::text LIKE 'aaaaaaaa-%' AND u.season_points > 0
ORDER BY u.season_points DESC LIMIT 15;

SELECT count(*) as total_runs_today
FROM public.run_history WHERE run_date = '2026-02-11';


-- === DAY 1 STATS ===
-- Runs today: 45
-- Flips today: 221
-- Points earned today: 221
-- Cumulative Points: Red 123 | Blue 82 | Purple 16
-- Hex Control: Red 56 | Blue 74 | Purple 16
-- Team sizes: Red 40 | Blue 40 | Purple 20